# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  push:
    branches:    
        - 'main'
        - 'k3s-with-services' 

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta_weather
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: underdefresco/getweather
      
      - name: Build and push Docker image underdefresco/weather
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./app/micro-svc-getWeather
          push: true
          tags: ${{ steps.meta_weather.outputs.tags }}
          labels: ${{ steps.meta_weather.outputs.labels }}



      - name: Extract metadata (tags, labels) for Docker
        id: meta_oauth
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: underdefresco/oauth
      
      - name: Build and push Docker image underdefresco/oauth
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./app/svc-oauth
          push: true
          tags: ${{ steps.meta_oauth.outputs.tags }}
          labels: ${{ steps.meta_oauth.outputs.labels }}
      

      - name: Extract metadata (tags, labels) for Docker
        id: meta_api
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: underdefresco/api
      
      - name: Build and push Docker image underdefresco/api
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./app/svc-api
          push: true
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta_latlon
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: underdefresco/getlatlon
      
      - name: Build and push Docker image underdefresco/getlatlon
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./app/micro-svc-getLatLon
          push: true
          tags: ${{ steps.meta_latlon.outputs.tags }}
          labels: ${{ steps.meta_latlon.outputs.labels }}

  pull_from_repo:
    name: Pull repo from GitHub
    runs-on: self-hosted
    needs: push_to_registry
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3


      - name: Apply secret to the  cluster 
        run: ls ../../../../
        working-directory: ./

      - name: Apply secret to the  cluster 
        run: kubectl apply -f ../../../../underdefresco_key.yaml
        working-directory: .

      - name: Apply modifications to the kubernetes config
        run: kubectl apply -f underdefresco.yaml
        working-directory: ./kubernetes/deployment/
        

